name: "Browser-Extension-Release-Chrome-Webstore"
on:
  push:
    branches:
      - master
    paths:
      - 'browser-extension/**'
  release:
    types: [created] 

jobs:
  chrome-extension:
    name: "zip-files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: browser-extension/
          dest: starfix-extension-chrome.zip

      - name: "publish extension on chrome webstore"
        uses: Klemensas/chrome-extension-upload-action@v1.3
        with:
          refresh-token: '1//0gWy_GbV_ZpLjCgYIARAAGBASNwF-L9IrYdkYTO4ye-jjWPLNRMHt97vZRPgbzuqgV8GrP0qvHrKm18DEyNn7p_CPtI4n7AfLfjk'
          client-id: '962194528619-v6o0covrffphhjeptjjbnve5d3j03fbs.apps.googleusercontent.com'
          file-name: ${{ github.workspace }}/starfix-extension-chrome.zip
          app-id: 'ojlhpgekmmemhihkigibkhehlejkjdmo'
          publish: true

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: starfix-extension-chrome.zip
          path: ${{ github.workspace }}/starfix-extension-chrome.zip
